# workflow 名称，可以自定义
name: Deploy GitHub Pages

on:
  # 触发条件：在代码 push 到 master 分支后，自动执行该 workflow
  push:
    branches:
      - master
  # 每天两点自动运行
  schedule:
    - cron: "0 2 * * *"

  # 可以手动执行
  workflow_dispatch:

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu，也可以自定义版本
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 Node.js 版本
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: |
          pnpm install

      # 生成静态文件
      - name: Build
        run: pnpm run docs:build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/.vuepress/dist
